resume:
  age:20
  name:aoho
  sex:male

server:
  port:8801
spring:
  application:
    name: configserver

---
spring:
  cloud:
    config:
      server:
        git:
          uri:https://github.com/xiaojia0314/cloud_config.git
          searchPaths: ${APP_LOCATE:dev}
